### ISSUE TITLE
Some of class was not created in src of three.js

### ISSUE THREAD

**Issue by sonygod** [haxiomic/haxe-threejs-template#4]
three.js  v 135

Some of class was not created in src of three.js

   ShapeGeometry.hx

I can find ShapeGeometry.d.ts in@types\three\src\geometries\ShapeGeometry.d.ts

**Comment by haxiomic** [comment]
It's generated
https://github.com/haxiomic/haxe-threejs-template/blob/master/.haxelib/three/0,135,0/three/ShapeGeometry.hx

The location of the haxe files is based on how they're exposed as types, rather than the originating js files
