### ISSUE TITLE
Compilation error occurs when using this template library to directly apply the official case code

### ISSUE THREAD

**Issue by FlowSand** [haxiomic/haxe-threejs-template#6]
Recently, I am using haxe+electron to develop an app. I need to use the Threejs library for 3D model rendering, so I noticed the dts2hx solution. I downloaded this template library and modified some code for testing. According to the official example (written in js), I found that the calling method of some official cases is not feasible in haxe, for example：
```
var dirLight = new DirectionalLight(0xffffffff);
dirLight.shadow.camera.top = -5;
dirLight.shadow.camera.left = -5;
```
The camera member in LightShadow is Camera type, while the top and left fields are defined in the OrthographicCamera class, which extends from camera. It cannot be called directly in haxe like js. Is there any other way to call it?

**Comment by haxiomic** [comment]
Hey @FlowSand!

You can use type casting, either of these works
```haxe
(cast dirLight.shadow.camera: OrthographicCamera).top = -5;
// or
var dirLightCamera: OrthographicCamera = cast dirLight.shadow.camera;
```

**Comment by FlowSand** [comment]
Thanks for answer，The first is what I want！:beer:
