### ISSUE TITLE
Is there a way cast to generic type without knowing T？

### ISSUE THREAD

**Issue by FlowSand** [haxiomic/haxe-threejs-template#7]
I'm practicing the offical case code, read fbx model and do something with it
```
object.traverse(function (child) {
     if ((child as THREE.Mesh).isMesh) {   
           // do something
    }
})
```
where in haxe THREE.Mesh is defined as
`extern class Mesh<TGeometry, TMaterial> extends Object3D<Event>`
I’cant just call(cast child: Mesh).isMesh, there will be “no enough parameters” error, what should i do?

**Comment by FlowSand** [comment]
Looks like I'm not skilled enough in web development and Haxe,After trying it out, I found that I can use the console to see the loaded stack of model objects and see their concrete types，and then，i can write like：
`(cast child : SkinnedMesh(BufferGeometry, MeshPhongMaterial))`,
On the other hand, it looks like this question is asking a bit odd

**Comment by FlowSand** [comment]
Since Haxe 4.0.0 some new features have been added, it is also possible to write:
```
var isMesh = js.Syntax.code("child.isMesh");
```
Although it is not suitable for some scenarios, I don't know if there is a better way for this case.

**Comment by haxiomic** [comment]
Heya, you can use `is` which will translate to js `instanceof` and doesn't require type parameters

When casting to a mesh, you could do `(cast obj: Mesh<Any, Any>)`, or if you want to supply information about the type params you can add info, for example, I care about the mesh material but not geometry here

```haxe
findDescendant(obj, obj -> {
	if (obj is Mesh) {
		var obj = (cast obj: Mesh<Any, three.Material>);
		if (obj.material != null && obj.material.name == name) {
			material = obj.material;
			return true;
		}
	}
	return false;
});
```

This is code from https://github.com/haxiomic/three-toolkit which might have useful references for you

I think I use `Std.is()` too, which is the same thing, but an older way of doing it

**Comment by FlowSand** [comment]
This is exactly what i want！Pretty thanks:thumbsup:
